### ISSUE TITLE
Re-analysis not failing with different broad bed on some samples

### ISSUE THREAD

**Issue by CooperNh** [sch-sdgs/SDGSPipeline#78]
Reanalysis ran to completion on Haems sample where the broad panel did not match the previous broad panel - MYH9 reanalysis for S1301836 (S1712725 StarLIMS) on run 1705988

**Comment by grovesn** [comment]
pipeline was removing NGSPatient.json if already existing but not recreating therefore did not fail on second reanalysis if BEDs did not match
